title: Ashkan Farhangi # your name (or website title) here
logo: "/images/portrait.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Engineering PhD student 
  <br>University of Central Florida<br>
   
  <br><br>
  <a href="https://www.linkedin.com/in/ashkan-farhangi-86a468192">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
